function transferOwnership() {
  fetch("/api/transfer-ownership", {
    method: "POST"
  })
    .then(res => res.json())
    .then(data => {
      document.getElementById("status").textContent = "Ownership transferred successfully!";
    })
    .catch(err => {
      console.error(err);
      alert("Ownership transfer failed.");
    });
}
